sonar.projectKey=juancho275_tractor-store
sonar.organization=juancho275
sonar.projectName=The Tractor Store
sonar.projectVersion=1.0.0

# Fuentes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Reporte JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones de cobertura — clases no testeables unitariamente
sonar.coverage.exclusions=\
  **/domain/model/**,\
  **/shared/config/**,\
  **/application/dto/**,\
  **/application/event/**,\
  **/TractorStoreApplication.java

# Exclusiones de análisis completo
sonar.exclusions=\
  **/TractorStoreApplication.java